spring.application.name=RabbitMq-Listener
server.port=8083
spring.docker.compose.enabled=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.listener.simple.default-requeue-rejected=false

app.rabbitmq.exchange=oficina.exchange
app.rabbitmq.queue=oficina.ordens-servico.criadas
app.rabbitmq.routing-key=oficina.ordem-servico.criada
